"""empty message

Revision ID: 94924d571534
Revises: b6101fd5072d
Create Date: 2024-03-06 00:40:35.421887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94924d571534'
down_revision = 'b6101fd5072d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
